### ISSUE TITLE
Golang Bindings

### ISSUE THREAD

**Issue by dustinblackman** [Kitt-AI/snowboy#122]
[Golang](https://golang.org/) bindings and a demo would be awesome for the Go community as something as high quality as snowboy doesn't quite exist. I'd be more then happy to take on the challenge myself if I can be pointed in the right direction.

**Comment by chenguoguo** [comment]
We haven't really played with Go, but it seems doable, see the swig documentation here: http://www.swig.org/Doc2.0/Go.html

Normally we use swig to convert the Snowboy library into the target language, see the example for Python here: https://github.com/Kitt-AI/snowboy/tree/master/swig/Python, or the example for Java here: https://github.com/Kitt-AI/snowboy/tree/master/swig/Java

It will be great if you can do the swig conversion and then the demo. You can put your swig script here `swig/Go`, and then your demo here `examples/Go`. Let us know if you have to use a specific version of swig, we normally use `3.0.10`. And thanks in advance!

**Comment by brentnd** [comment]
FWIW, I attempted to created a swig conversion and example for snowboy-detect over the weekend but ran into a lot of issues with swig Golang support, specifically for std::unique_ptr.

**Comment by xuchen** [comment]
@brentnd could you please post your code and errors?

**Comment by brentnd** [comment]
https://github.com/brentnd/snowboy/tree/master/swig/Go: has the makefile and swig file. Right now, the makefile is building and the example actually builds fine but segfaults on the first call to any C++ code (`NewDetector`). Obviously the example isn't going to do anything, but didn't want to invest in that until I have the other issues addressed.

https://github.com/brentnd/snowboy/tree/swigcxx/examples/Go: Go also has the ability to define a package with a swig file (i.e. `snowboydetect.swigcxx`) and it will recognize that and build it when it gets installed by someone including it with `go get`. However, with that method it was not building due to 
```../../swig/Go/../../include/snowboy-detect.h:125:8: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
   std::unique_ptr<WaveHeader> wave_header_;
        ^
../../swig/Go/../../include/snowboy-detect.h:126:8: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
   std::unique_ptr<PipelineDetect> detect_pipeline_;```

**Comment by xuchen** [comment]
Could you please give detailed commands to run those files and re-produce the errors? I'm not familiar with Go and don't know where to start yet.

**Comment by brentnd** [comment]
I just found https://github.com/lian/snowboy which appears to do what i was unable to do. I haven't had time to check it out but could be helpful moving forward.

**Comment by dustinblackman** [comment]
@brentnd Unfortunately it doesn't work, it seems to result in the same problems both you and I are having. 

I had started working on this the day I posted the issue, but unfortunately have run in to the same problems that @brentnd had with not being able to build with the module after (on OSX at least). Don't mind the random stuff in the swig file, I was kind of attempting everything to see what breaks. https://github.com/dustinblackman/snowboy/tree/go-bindings/swig/Go

@xuchen My makefile I have in my repo will take care of building and installing the module in a directory that makes sense for Go. Afterwards, you can create a new folder something like `$GOPATH/src/github.com/xuchen/snowboytest`, and stick this `main.go`. 

```go
package main

import "github.com/Kitt-AI/snowboydetect"

func main() {
	s = new(snowboydetect.SnowboyDetect)
}
```

Afterwards, you can run `go build`. You'll see the build failing with the current progress.

**Comment by brentnd** [comment]
From @dustinblackman and the lian example I was able to get something that seems to work. All it does at this point is return -2 (silence) every couple hundred milliseconds but no errors, so that's progress.

https://github.com/brentnd/snowboy

Another thing to consider, @dustinblackman mentioned his makefile does an "install" to copy some files to the top level of Kitt-AI/snowboy. With the makefile version, this would've worked, but with the working version, go actually handles the swig building because it finds the .swigcxx file in the package. However, as it stands, the import path would be something like `github.com/Kitt-AI/snowboy/swig/Go`. It could be okay, but is unconventional to have it nested so far and the package name not match the directory.

**Comment by xuchen** [comment]
@brentnd did you get detection to work? If you could submit a concrete example as a PR, we'd very much appreciate it!

**Comment by brentnd** [comment]
I hope to do some more work on this next week with a good example and working detection.

**Comment by brentnd** [comment]
For those interested in the Go bindings, I've been writing a wrapper around the swig Go bindings to provide a Go-style interface to snowboy.

You can find it here: https://github.com/brentnd/go-snowboy.

The swig stuff works for getting access to using the raw C++ interface but the calls to the swig-generated Go code are convoluted because the C++ code has overloaded functions and the data types for C++ `std::vector`s and raw pointers don't map to native Go types.

**Comment by chenguoguo** [comment]
@brentnd great!
