### ISSUE TITLE
ubuntu 16.04.1 electron

### ISSUE THREAD

**Issue by sakirtemel** [Kitt-AI/snowboy#126]
Hi,

I'm struggling with using snowboy and electron. In package json, I have electron(1.4.7), electron-rebuild(latest), and snowboy (1.1.0). After npm install I'm running this to rebuild the modules

`./node_modules/.bin/electron-rebuild --pre-gyp-fix`

And when I run electron, it's giving me this error

`/home/app/node_modules/electron/dist/electron js/electron.js dev: symbol lookup error: /home/app/node_modules/snowboy/lib/node/binding/Release/electron-v1.4-linux-x64/snowboy.node: undefined symbol: cblas_sdot`

I installed almost everything after a clean install, but still no chance
(sox libatlas-base-dev libblas-dev liblapack-dev portaudio19-dev libatlas-base-dev swig3.0 python-pyaudio python3-pyaudio sox libsox-fmt-all libmagic-dev libatlas-base-dev sox libsox-fmt-all)

node version: 6.9.5
npm version: 3.10.10

**Comment by evancohen** [comment]
Can confirm this issue! What's weird is that you can clone the snowboy repo, `npm install`, and run the example without a problem. The issue finding `cblas_sdot` only appears after rebuilding the module for electron.

I've seen this a number of times in the past and it's because, for some reason unknown to me, g++ decides not to bind things correctly.

I managed to link the libraries by adding `-Wl,--no-as-needed` to the `libraries` section of `./node_modules/snowboy/binding.gyp` [like this](https://github.com/Kitt-AI/snowboy/pull/57/files) and re-running  
` ./node_modules/.bin/electron-rebuild --pre-gyp-fix`. 

Give that a shot and let me know if it works for you too.

**Comment by sakirtemel** [comment]
@evancohen thanks, it worked! you need to add `-Wl,--no-as-needed` just before `-lcblas` as shown in the link.

**Comment by evancohen** [comment]
Came up with a better solution (I think), if you are curious. Just drop this [.npmrc](https://github.com/evancohen/sonus-electron-boilerplate/blob/master/.npmrc) into the root of your project, delete your existing `node_modules` and run 
```
HOME=~/.electron-gyp npm install
```

That should preserve the `cblas_sdot` binding and will build all of the native modules for your project for Electron.

**Comment by evancohen** [comment]
@chenguoguo I'd like to take a stab at having Travis build binaries for Electron. Is this something you'd be interested in?

**Comment by chenguoguo** [comment]
@evancohen yeah feel free to submit a PR!
