### ISSUE TITLE
Creating umdl ? how ? tools needed? File Format ? 

### ISSUE THREAD

**Issue by SpeakUpper123** [Kitt-AI/snowboy#169]
Hello can we have a little more insight about umdl vs pmdl ?
how is a umdl created ? what is needed for it ?
I found that pmdl is almost unusable it simply does not recognize my pmdl created keywords.
What is needed to create a umdl myself ? Why 500 examples needed and no possibility to make one with 10 examples to convert umdl myself ? Release tools ?
Can you describe what method and "wav" file format is exactly needed to get a precize working pmdl?

thanks in advance

**Comment by chenguoguo** [comment]
If it's performing like what you described, then something is wrong when you created the pmdl.

pmdl stands for `personal model`. It only works well for the person who provides the audio samples, and it works well when you use the same microphone to record the words test the words.

Most likely, you have a mis-matched microphone, or you are using your pmdl for other people. It's also possible that you have noise or click sound around your recorded audios, and removing those manually should improve the performance quite a bit.

Regarding the umdl, that stands for `universal model`. Current you cannot create the umdl by yourself. We do have a service for training that (email snowboy@kitt.ai if you are interested in that service). Training a umdl with 10 samples does not really make sense, because it won't work well. If you look at modern speech recognizer, that requires thousands of hours of data. Speech recognition is not that easy.

**Comment by SpeakUpper123** [comment]
Thank you for your fast answer. Could you please explain what exact format: mono / Stereo / Bitrate / max size channels etc is suggested for creating a precize and good pmdl ? thanks

**Comment by chenguoguo** [comment]
16k sampling rate, 16 bit linear signed integer, single channel. Make sure you don't have noise around the word itself. The website support uploading audio files, so you can manually clean it up and upload it to the website for testing purpose.

**Comment by SpeakUpper123** [comment]
thank you for the "precize" answers =)

**Comment by chenguoguo** [comment]
Internal we have different algorithms for personal models (pmdl) and universal models (umdl). All those algorithms were developed internally and I don't think there are open sourced version of those.

**Comment by bradchesney79** [comment]
@SpeakerUpper123 ...they provide sample .umdl files, you could always open them in some kind of editor and compare the contents with a .pmdl . Otherwise, this is a feature they have chosen to monetize-- so they can eat and pay bills, which is wholly acceptable (to be paid for working).

**Comment by Dipendra77** [comment]
How many voice models do i need to provide to create my own universal model?
