### ISSUE TITLE
Android README references future 1.2.0, but 1.2.0 is released?

### ISSUE THREAD

**Issue by peternann** [Kitt-AI/snowboy#186]
i.e. See the bottom of here:
https://github.com/Kitt-AI/snowboy/tree/master/examples/Android

It talks about features to be in 1.2.0, but 1.2.0 is released, but doesn't mention these features.
Did they make it into 1.2.0 or not?

Reason for my query:
I don't want to revisit Snowboy on Android until a newer NDK is supported, and preferably the 'Hard' floating point thing is addressed.

Can you guys please clarify in the docs the status of Android nowadays?

Thanks! (P.S. Sorry if I missed it somewhere, but the docs still need updating either way..)

**Comment by chenguoguo** [comment]
It has 1.2.0 and it supports soft float.

**Comment by xuchen** [comment]
i revised the README. All TODOs were done a month ago and updated in `master`. Thanks for pointing it out.

**Comment by peternann** [comment]
Awesome. Thanks guys.
Will give Android another spin.
Support for newer Android NDKs might make dev on Windows a bit more possible. I'll let you know how I go!

**Comment by xuchen** [comment]
Unfortunately we do not support developing on Windows. This is the first
sentence in the Android readme.

On May 8, 2017 3:58 PM, "peternann" <notifications@github.com> wrote:

Awesome. Thanks guys.
Will give Android another spin.
Support for newer Android NDKs might make dev on Windows a bit more
possible. I'll let you know how I go!

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/Kitt-AI/snowboy/issues/186#issuecomment-300014127>, or mute
the thread
