### ISSUE TITLE
Raspbian 8

### ISSUE THREAD

**Issue by ericlfr** [Kitt-AI/snowboy#266]
Hi,

I try to launch a demo.py from "snowboy-master\examples\Python"

Here is the result:

 python demo.py snowboy.umdl -d
Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    import snowboydecoder
  File "/home/pi/snowboy-master/examples/Python/snowboydecoder.py", line 5, in <module>
    import snowboydetect
  File "/home/pi/snowboy-master/examples/Python/snowboydetect.py", line 1
    ../../swig/Python/snowboydetect.py
    ^
SyntaxError: invalid syntax

I changed the snowboydetect.py from

../../swig/Python/snowboydetect.py

to

import sys
sys.path.append("../../swig/Python")
import snowboydetect

and here is the result:

 python demo.py snowboy.umdl -d
Traceback (most recent call last):
  File "demo.py", line 27, in <module>
    detector = snowboydecoder.HotwordDetector(model, sensitivity=0.5)
  File "/home/pi/snowboy-master/examples/Python/snowboydecoder.py", line 90, in __init__
    self.detector = snowboydetect.SnowboyDetect(
AttributeError: 'module' object has no attribute 'SnowboyDetect'

I've been able to verify that SnowboyDetect is in file "/home/pi/snowboy-master/swig/Python/snowboydetect.py"

I do not understand what happens :-/

Could you help me please?

**Comment by chenguoguo** [comment]
From the back slash it seems that you are using windows... we don't support windows

**Comment by ericlfr** [comment]
I'm working on raspian (back slash / ) not windows ( anti slash \)

**Comment by chenguoguo** [comment]
but then where did you get this? `snowboy-master\examples\Python`

Also, did you make under `swig/Python`?

**Comment by ericlfr** [comment]
I have done a make under swig/Python with swig version = 3.0.12

**Comment by chenguoguo** [comment]
Did you change `examples/Python/snowboydetect.py` by any chance? That file was generated by swig automatically and the first line is not `../../swig/Python/snowboydetect.py`. Your error message seems to suggest that the first line is `../../swig/Python/snowboydetect.py`

**Comment by TomZhang1124** [comment]
> Did you change `examples/Python/snowboydetect.py` by any chance? That file was generated by swig automatically and the first line is not `../../swig/Python/snowboydetect.py`. Your error message seems to suggest that the first line is `../../swig/Python/snowboydetect.py`

Brother, my device is the orange pie 5ubuntu20.0.04. When I ran demo, the syntax error was prompted. I tried all kinds of methods, but the problem was the same. I come from China, my English is not very good, I did not understand the solution, please help me to see, thank you. Brother, my device is orange pie 5Ubuntu 20.0.04, go to run demo
orangepi@orangepi5:/usr/src/snowboy/examples/Python3$ python3.8 demo.py resources/models/snowboy.umdl
Traceback (most recent call last):
File "demo.py", line 1, in
import snowboydecoder
File "/usr/src/snowboy/examples/Python3/snowboydecoder.py", line 5, in
import snowboydetect
File "/usr/src/snowboy/examples/Python3/snowboydetect.py", line 1
../../swig/Python3/snowboydetect.py
^
SyntaxError: invalid syntax

resources and other files in this example /Python3 seem to be redirects. My environment doesn't seem to be able to parse this
