### ISSUE TITLE
android port does not work with ndk 12 

### ISSUE THREAD

**Issue by fuzzelfish** [Kitt-AI/snowboy#28]
"Removed support for the armeabi-v7a-hard ABI",

maybe add a comment somewhere, it took me a few moments to realize

**Comment by chenguoguo** [comment]
Thanks for point this out! I added a few words in README.md to reflect this. I will also look into ways to support ndk r12.

**Comment by peternann** [comment]
Isn't it just a matter of recompiling your library with the 'hard' option removed?

My understanding is that AOSP removed this 'hard' version of the library precisely because people were errantly using it for performance gain, when the gain was actually marginal (and mis-understood), but the hassle of incompatible libraries (as we are seeing here with Snowboy), was extreme at times.

Snowboy can't only work on an old NDK forever...

Any movement in fixing the problem here?
