### ISSUE TITLE
Low volume for custom wakeword interactions

### ISSUE THREAD

**Issue by AdvaitT17** [Kitt-AI/snowboy#281]
when I use the wakeword the volume is quite enough but when assistant responds the volume is very less, I even edited the assistant.py and changed  self.volume_percentage = 80 from 50....but nothing happened.

**Comment by chenguoguo** [comment]
What is assistant.py? Are you using other repositories?

**Comment by AdvaitT17** [comment]
Now snowboy only

**Comment by AshokRawatBLR** [comment]
Has anyone tried Snowboy with telephony speech (instead of using mic input) using any of the VoIP codecs like AMR-WB, EVS or OPUS? We are trying feeding decoded speech buffer to Snowboy and seeing ~50% drop in detection ratio v/s when using mic input directly (tried with universal model "alexa"). There may be some issue with our application code, trying to figure it out. Please share experience  if someone has already tried it.
