### ISSUE TITLE
Better rules to choose the hotword.

### ISSUE THREAD

**Issue by Smanar** [Kitt-AI/snowboy#29]
Hi, I m using your engine in a C++ project (for the moment it's more C) without problems, but I need to use a trick to reduce false positive.
It's perhaps due to microphone but if a record the word "momomo" I have a trigger when I say "tatata" (even with 0.5 sensitivity).
IDK how work your algorithm, but what can I do to choose a better Hotword. Its better to use long word/short word more vowel/more consonant, simple word+blank+simple word, ...

**Comment by chenguoguo** [comment]
Yes it's definitely better to use long and unique word/phrases. We should
probably add it to the documentation. Thanks for pointing this out.

**Comment by Smanar** [comment]
And for vowel/consonant choose, it doesn't have impact on it ?
Some "sound" aren't better then other ?
It's better to use same vowel 2/3 time in the word, or the more different possible ?

Or only the lenght have impact on the result ?

**Comment by chenguoguo** [comment]
Things like vowel/consonant choice will affect the performance, yes, but
may not be a lot. Your intuition should be correct to some extent, but we
don't have a chart showing the performance difference of different
vowel/consonant combination, so I don't feel like giving a suggestion on
this yet. Also, if we suggest one "sound" over another, that may not hold
if we update the model in the future :-) We do suggest developers trying
different hotwords though. And please keep giving us suggestions like this
to make it a better tool, thanks!

And for vowel/consonant choose, it doesn't have impact on it ?
Some "sound" aren't better then other ?
It's better to use same vowel 2/3 time in the word, or the more different
possible ?

Or only the lenght have impact on the result ?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Kitt-AI/snowboy/issues/29#issuecomment-230143081>, or mute
the thread
<https://github.com/notifications/unsubscribe/ALPfk_Ddzi48QPd4xMpiOk1PJ63012aUks5qR3pYgaJpZM4JDtnu>
.

**Comment by Smanar** [comment]
Lol, thx a lot, I will continue my tests for fun, but since I don't know how works your engine, Is totaly random ^^.
In fact It's not really a problem, I m using a trick. With 2 hotwords, after the first one I have 3/4 s to say the second one, else it reset. With that I have only 1/2 false positive in a complete day, but it's realy frustrating when the engine mix some word as differents as "momomo" and "tatata".

But nevermind my project works fine with it,so powerful and too easy to set up.

**Comment by chenguoguo** [comment]
Love your trick, by probability it will reduce false positive quite a lot
:-)

We will keep imoroving the model. Hopefully in the future it will better
handle things like momomo. Our model is a currently trained on human
speech, not "sound".
On Jul 4, 2016 10:04 AM, "Smanar" <notifications@github.com> wrote:

Lol, thx a lot, I will continue my tests for fun, but since I don't know
how works your engine, Is totaly random ^^.
In fact It's not really a problem, I m using a trick. With 2 hotwords,
after the first one I have 3/4 s to say the second one, else it reset. With
that I have only 1/2 false positive in a complete day, but it's realy
frustrating when the engine mix some word as differents as "momomo" and
"tatata".

But nevermind my project works fine with it,so powerful and too easy to set
up.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Kitt-AI/snowboy/issues/29#issuecomment-230328563>, or mute
the thread
<https://github.com/notifications/unsubscribe/ALPfk6tINbGJtBkrq6CKGj3QrND_5ATeks5qST0kgaJpZM4JDtnu>
.

**Comment by chenguoguo** [comment]
I'll add some suggestions on how to choose a hotword. Colsing this issue.
