### ISSUE TITLE
Silence Detection

### ISSUE THREAD

**Issue by sammachin** [Kitt-AI/snowboy#3]
Awesome project guys, I'm the author of the orignal RaspberryPi Alexa project :)

I'm looking at integrating your code into AlexaPi, one thing I need to work out is silence detection, have you got any tips?

The flow would need to go WakeWord>Record Command>DETECT END OF COMMAND>Post to Alexa Voice Service.

**Comment by Timmmm** [comment]
They keyword to search for is VAD (Voice Activity Detection). There are quite a lot of them available, often codecs contain them (e.g. Opus has one).

Here are a couple I found by Googling "github VAD":

https://github.com/mwv/vad

https://github.com/shriphani/Listener/blob/master/VAD.py

**Comment by chenguoguo** [comment]
Great work on the RaspberryPi Alexa project @sammachin !

Yes one way is to try the third party VAD tools as @Timmmm mentioned.

However, Snowboy does have internal VAD. I just updated the internal code so that the RunDetection() function will return -2 if silence is detected. We will update the library in this repository asap. You may have to smooth the VAD output a little bit, e.g., call it the end of a sentence after receiving several -2's instead of just -2.

Another way is to have a stop hotword, e.g., you say the sentence like "Alexa, turn on the lights, thanks." and you let Snowboy detect both "Alexa" and "thanks".

**Comment by xuchen** [comment]
I updated the entire codebase with new VAD support and compiled binaries (v1.0.1). Now the return value of ``SnowboyDetect.RunDetection()`` (see `snowboydecoder.py` for detailed usage) function indicates silence, voice, error, and triggered words:

| return | meaning         |
|--------|-----------------|
| -2     | silence         |
| -1     | error           |
| 0      | voice           |
| 1,...  | triggered index |

Snowboy's VAD model has two layers: first layer is energy based, just like the above sampled examples; second layer is trained with neural networks to specifically recognize human voice.

**Comment by GemBro** [comment]
Yes yes ... glad you guys are now talking together on this ...
