### ISSUE TITLE
Failure on Build in Stretch

### ISSUE THREAD

**Issue by gbCambridge** [Kitt-AI/snowboy#323]
Hi,
I have installed a DAC Hat board on my rpi. This has not interfered with the Alexa implementation....the voice still comes from the 3.5mm jack on the rpi pcb.
However, when I run wakeword with sudo ./wakeWordAgent -e kitt_ai I get the following:

INFO:main: Starting Wake Word Agent
INFO:WakeWordAgent: State set to IDLE(2)
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.front.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory

etc..........................................................

When I check the Playback devices I get the following:
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
Subdevices: 8/8
Subdevice #0: subdevice #0
Subdevice #1: subdevice #1
Subdevice #2: subdevice #2
Subdevice #3: subdevice #3
Subdevice #4: subdevice #4
Subdevice #5: subdevice #5
Subdevice #6: subdevice #6
Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
Subdevices: 1/1
Subdevice #0: subdevice #0
card 2: sndrpihifiberry [snd_rpi_hifiberry_dacplus], device 0: HiFiBerry DAC+ HiFi pcm512x-hifi-0 []
Subdevices: 1/1
Subdevice #0: subdevice #0

As you can see the device that Wakeword is seeking is there, but not identified in a manner that is accepted by Wakeword. Alexa itself is happy to use these settings. So far I have not been able to identify the culprit that zeroes the devices, but in the short term, I am wondering how best to get over this problem.
Alternatives seem to be ......1) Fix the device descriptions, 2) Fix wordwake to be more compatible with the way Alexa (apparently) works......Alexa is unaffected by these settings 3)...here I await your suggestions :-)

Any thoughts on the best way forward gratefully received

George

**Comment by chenguoguo** [comment]
First of all, audio capturing is not part of wake word detection. As long as you can feed audio (16bit signed integer, 16k sampling rate, single channel) to the wake word detection engine, it should work. So technically you can "route" the audio that works for Alexa, to the wake word engine, and it should just work.

With that said, the Alexa sample app uses PortAudio for capturing audio for the wake word engine, and the issue is really with PortAudio. Sometimes, people find that if you run the program with `sudo`, it will not work properly. Perhaps, you can try to run it without `sudo`.

**Comment by gbCambridge** [comment]
Hi...fixed it...I installed manually the latest versions of Als and PortAudio...and the problems went away!!!!!
