### ISSUE TITLE
Use Snowboy in avs-device-sdk

### ISSUE THREAD

**Issue by cookydent** [Kitt-AI/snowboy#379]
Hi all,

as the [alexa-avs-samle-app](https://github.com/alexa/alexa-avs-sample-app) is in maintenance mode, I successfully used the [avs-device-sdk](https://github.com/alexa/avs-device-sdk/wiki) to implement Alexa on a RPi3. Even though I was able to get it up and running, I am wondering how to change the hotword using my personal pmdl-file I generated to this end. The provided steps apply for the sample-app but I was not able to reproduce them for the device-sdk. Is it even possible?

Thanks!
Conrad

**Comment by cookydent** [comment]
I was finally able to figure it out. The following changes to /avs-device-sdk/SampleApp/src/SampleApplication.cpp have to be made when building the SampleApp:

- Adjust KITT_AI_SENSITIVITY and KITT_AI_APPLY_FRONT_END_PROCESSING as described.
- Change the path to your own pmdl-file at the bottom accordingly.

Runs like a charm! Thx again

**Comment by cucubits** [comment]
Hi Cookydent,

I'm pretty new at this and I'd like to ask for a little help. Since the avs sdk default step by step install procedure uses Sensory, would you mind writing here the steps you took to get it working on a rpi3 with Snowboy? (I'd like to see the snowboy install/git commands you used, any other configuration for it, the dependencies and how you set up the sdk make command).

A bit of background: I did manage to install avs sdk with sensory and it works well but I'd like to use snowboy to be able to use my own wake word. 


Thank you!

**Comment by 0PK** [comment]
@cookydent 
I am struggling also quite some time to get kitt_ai working with the sdk: if you could describe your steps, that would be super.

**Comment by chenguoguo** [comment]
We will submit a PR to the Alexa SDK soon, which hopefully will make it easier to use Snowboy in Alexa.

**Comment by Puneethbandikatla** [comment]
Hi @cookydent , 
 Can you please be specific where you've changed the path to the .pmdl file.

Thanks,
