### ISSUE TITLE
add -infile option to read from pre-recorded wav file

### ISSUE THREAD

**Issue by Sispheor** [Kitt-AI/snowboy#47]
For testing, I would like to record my voice and give the recorded sample to snowboy for testing my script without having to speak into my microphone everytime.

On pocket_sphinx continus there is an option to do that
`pocketsphinx_continuous -infile file.wav`

**Comment by chenguoguo** [comment]
This is easily doable, but you might have to modify the code a little bit.

Taking the [C++ demo](https://github.com/Kitt-AI/snowboy/blob/master/examples/C%2B%2B/demo.cc) as an example, 
```
  std::cout << "Listening... Press Ctrl+C to exit" << std::endl;
  std::vector<int16_t> data;
  while (true) {
    pa_wrapper.Read(&data);
    if (data.size() != 0) {
      int result = detector.RunDetection(data.data(), data.size());
      if (result > 0) {
        std::cout << "Hotword " << result << " detected!" << std::endl;
      }
    }
  }
```
What you have to do is, instead of reading the data using `pa_wrapper.Read(&data);` which calls PortAudio and captures audio through the microphone, you should read the data from audio file. Make sure your audio file is in the correct format (16k sampling rate, 1 channel, 16 bit signed integer), linear PCM.
