### ISSUE TITLE
Error initializing streams or reading audio data

### ISSUE THREAD

**Issue by purpleblues** [Kitt-AI/snowboy#79]
In snowboydecoder.py, I have issue that

`ans = self.detector.RunDetection(str(data))` 

returns -1, printing `"Error initializing streams or reading audio data"`

I compiled the _snowboydecoder.so with python3.4 on raspberry pi and ran it with python3

Input is USB webcam mic.

**Comment by chenguoguo** [comment]
This usually means the audio passed to the decoder was malformatted. What was your platform? Did you try this in a virtual environment? The Python3 is not well tested so I'll have to test this as well.

**Comment by purpleblues** [comment]
@chenguoguo I didn't run it on virtual environment. But almost same code and same hardware environment that run on Python 2 works well.

And I used `str(data)` because RunDetection() didn't allow it to pass `bytes`. Is this might the problem?

**Comment by chenguoguo** [comment]
@purpleblues this will certainly case probably, because when you do `str(data)` in python 3 it will convert the data to a unicode string which will be different from the audio data.

The part I don't understand is that you said "RunDetection() didn't allow it to pass `bytes`". This indicates that the library was not compiled correctly. Could you try a virtual environment and make sure you compile the swig part with Python3? You have to make sure that `python-config` is linked to your Python3 not Python2.

**Comment by chenguoguo** [comment]
Cross reference:

https://github.com/Kitt-AI/snowboy/issues/35

https://groups.google.com/a/kitt.ai/forum/#!topic/snowboy-discussion/3G0fobzUw-0
